version: "3"
services:
  sonarqube:
    image: sonarqube:8.6-community
    ports:
      - 9000:9000
    networks:
      - jenkinsnetwork
  jenkins:   
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    networks:
      - jenkinsnetwork
networks:
  jenkinsnetwork: